# Generated by Django 3.0 on 2024-12-20 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=50)),
                ('palce', models.CharField(max_length=15)),
                ('pin', models.CharField(max_length=6)),
                ('post', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=10)),
                ('palce', models.CharField(max_length=15)),
                ('pin', models.CharField(max_length=6)),
                ('post', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=10)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('slot', models.CharField(max_length=10)),
                ('DOCTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('feedback', models.CharField(max_length=150)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('feedback', models.CharField(max_length=150)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login'),
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('file', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200)),
                ('APPOINTMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Appointment')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='SCHEDULE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Schedule'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
    ]
