# Generated by Django 3.0 on 2024-12-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='from_time',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='to_time',
            field=models.CharField(max_length=150),
        ),
    ]
