# Generated by Django 3.0 on 2024-12-27 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20241227_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='palce',
            new_name='place',
        ),
    ]
