# Generated by Django 3.0 on 2025-01-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_schedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tocken',
            field=models.BigIntegerField(default='0'),
        ),
    ]
