# Generated by Django 3.0 on 2025-01-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_appointment_tocken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='slot',
            field=models.BigIntegerField(default='0'),
        ),
    ]
