# Generated by Django 3.2.25 on 2025-02-12 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20250103_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='DOCTOR',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor'),
        ),
    ]
